# Generated by Django 6.0.5 on 2026-05-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nome_categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('idProduto', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('favorito', models.BooleanField(default=False)),
                ('categorias', models.ManyToManyField(related_name='produtos', to='produtos.categoria')),
            ],
        ),
    ]
