# Generated by Django 6.0.5 on 2026-06-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_imagem_produto_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='avaliacao',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='produto',
            name='ingredientes_base',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='ingredientes_creme',
            field=models.TextField(blank=True, null=True),
        ),
    ]
