# Generated by Django 6.0.5 on 2026-05-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfis/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
