# Generated by Django 6.0.5 on 2026-05-29 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0002_usuario_foto_perfil_usuario_nome_completo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='foto_perfil',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nome_completo',
        ),
    ]
